version: "3.3"
services:
    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443

    wordpress:
        depends_on:
            - mysql
        image: wordpress:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: ft_services_user
            WORDPRESS_DB_PASSWORD: ft_services_pass
            WORDPRESS_DB_NAME: ft_services_db
        # container_name: wordpress
        networks:
            - ft_services_network

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ft_services_pass_root
            MYSQL_USER: ft_services_user
            MYSQL_PASSWORD: ft_services_pass
            MYSQL_DATABASE: ft_services_db
        volumes:
            - mysql_data:/var/lib/mysql
        # container_name: mysql
        networks:
            - ft_services_network

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - ft_services_network


volumes:
    mysql_data:
networks:
    ft_services_network:
        driver: bridge
