apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: cacharle-nginx
          imagePullPolicy: Never
          name: cacharle-nginx-container
          ports:
            - containerPort: 80
              hostPort: 9080
            - containerPort: 443
              hostPort: 9443
            - containerPort: 22
              hostPort: 9022

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9080
      targetPort: 80
    - name: https
      port: 9443
      targetPort: 443
    - name: ssh
      port: 9022
      targetPort: 22
  selector:
    app: nginx
