apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: cacharle-phpmyadmin
          imagePullPolicy: Never
          name: cacharle-phpmyadmin-container

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  ports:
    - name: http-phpmyadmin
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
