apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - image: cacharle-ftps
          imagePullPolicy: Never
          name: cacharle-ftps-container

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  type: LoadBalancer
  ports:
    - name: ftps
      targetPort: 21
      port: 21
    - name: ftps-data
      targetPort: 21000
      port: 21000
  selector:
    app: ftps
  # loadBalancerIP: 192.168.99.240
