apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - image: ftps-service
          imagePullPolicy: Never
          name: cacharle-ftps-container

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
    - name: ftps
      targetPort: 21
      port: 21
    - name: ftps-data
      targetPort: 21000
      port: 21000
  selector:
    app: ftps
